### ISSUE TITLE
Measurements never stop?

### ISSUE THREAD

**Issue by bortzmeyer** [RIPE-NCC/ripe-atlas-tools#5] opened 2015-09-20 19:08 UTC
I've started two measurements, ping (2437452) and DNS (243745) and, 15 or 20 minutes later, the command still did not yield back to the shell.

**Comment by danielquinn** [comment] 2015-09-21 15:21
There's currently a problem where you ask for `n` probes and the streaming response returns `n-1`.  As a result, since we're waiting for `n` responses, it never hangs up.  I'll need to dig into where the problem is before I can fix this one.

**Comment by bortzmeyer** [comment] 2015-09-21 15:30
Indeed, my experience is that the problem is uncommon when I request a handful of probes and much miore frequent when I request dozens of probes.

I spent some time on this problem when developing my own CLI (which now works fine) so I suggest you look at the code in https://github.com/RIPE-Atlas-Community/ripe-atlas-community-contrib/blob/master/RIPEAtlas.py specially the results() method.

**Comment by danielquinn** [comment] 2015-10-01 16:57
I've added a `timeout=` keyword argument to the `Stream` class, to allow for a sort of rolling timeout value.  Now, when we run `measure` it will still execute a stream, but if it doesn't receive results for `timeout + 1` seconds, it'll disconnect, assuming that all results that *can* come back in a reasonable time, have already done so.  Currently, timeout is set to 5 minutes, which I figure is pretty generous.

I'm going to close this issue now, but if you think the behaviour is still broken, please feel free to re-open.

**Closed by danielquinn** 2015-10-01 16:57 UTC
